sylius_grid:
    grids:
        viweb_lexicon:
            driver:
                name: doctrine/orm
                options:
                    class: Viweb\LexiconBundle\Entity\Entry
            fields:
                term:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                        label: sylius.ui.create
                        icon: 'icon-external-link'
                        options: { }
                item:
                    update:
                        type: update
                        label: sylius.ui.edit
                        options: { }
                    delete:
                        type: delete
                        label: sylius.ui.delete
                        options: { }