services:
    viweb_lexicon.admin_menu_listener:
        class: Viweb\LexiconBundle\EventListener\ConfigureAdminMenuListener
        tags:
          - { name: kernel.event_listener, event: viweb_system.menu_admin_configure, method: onMenuConfigure }
