viweb_admin_lexicon:
    resource: |
        alias: viweb.lexicon
        redirect: update
        except: ['show', 'update']
        section: admin
        templates: ViwebSystemBundle:Crud
        grid: viweb_lexicon
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'outline'
    type: sylius.resource

viweb_admin_lexicon+update:
    path: /lexicons/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: viweb.controller.lexicon:updateAction
        _sylius:
            section: admin
            template: ViwebSystemBundle:Crud:update.html.twig
