<?php

namespace Viweb\LexiconBundle\Repository;

/**
 * EntryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
